export enum CommResultType {
    InvalidChannel     = 'res:invalid_cnl',

    // Error occured while passing message to system, generated by the frontend
    CommunicationError = 'res:comm_err',

    // The last-resort *502 Internal Server Error*
    SystemError        = 'res:sys_err',

    // A General Purpose "invalid user input" type of error, shown directly to user
    ChannelError       = 'res:cnl_err',

    // A successful message
    ChannelResponse    = 'res:cnl_resp',
};

export enum AppChannel {
    Suppliers = 'scnl:supl',
    Inventory = 'scnl:inv',
};
